### ISSUE TITLE
vcp can't work well

### ISSUE THREAD

**Issue by zer00o** [RadioOperator/Yet_Another_Bootloader#1]

**Comment by zer00o** [comment]
The VCP of "SLV3APP1_DAPv1_HID+VCP" and "SLV3APP2_DAPv2WinUSB+VCP" in which "STLINKv3_YAB",can't work well.
By testing of following:
Short-circuit RX and TX pin of stlinkv3,
1.plug into usb,open serial port software ,then send and receive automatically.
2.check the data receiving from the serial port software.
After several tests on step1 and step2,half of the tests can work well,but of them can not.

**Comment by RadioOperator** [comment]
我在没有YAB的STLINK上面测试过HID+VCP，工作正常，没有发生你说的问题。
我用的PC串口程序是SSCOM5.13.1 。

测试YAB用的固件，我最近在忙别的事情，等我有空再试一试。

**Comment by zer00o** [comment]
好的，非常感谢，另外发现, stlinkv3刷SLV3APP2_DAPv2WinUSB+VCP
将被调试单片机写入一个上电一直发送串口数据的程序，连接好硬件，插上stlinkv3的usb，会出现串口无法使用。
将被调试单片机写入一个一直发送串口数据的程序在入口加入延时1-2秒，插上stlinkv3的usb，则能够很好工作。

**Comment by RadioOperator** [comment]
谢谢，我查一查，应该是CDC的初始化做得不好。

**Comment by RadioOperator** [comment]
@zer00o  Hi，请有时间试一试我的新的固件（见附件）。
我修改了VCP的UART底层驱动，由RTE改为HAL的DMA模式。
如果解决了这个bug，我会更新源码。谢谢。

[Build.zip](https://github.com/RadioOperator/Yet_Another_Bootloader/files/6408782/Build.zip)

**Comment by RadioOperator** [comment]
no more follow-up.
